### ISSUE TITLE
Can't find piwik.js

### ISSUE THREAD

**Issue by yizreel-Chen** [scholarsportal/dataverse-data-explorer-v2#11]
Hi, I am integrating data-explorer as an external tool for dataverse. After finishing the installation, I ingested a tab file to test it. When I click the explore button, it shows:
![image](https://user-images.githubusercontent.com/58657543/160869708-e6de13b4-ddd4-4a80-95b1-a260d44e2e48.png)
It seems that it couldn't find the piwik.js file and my metadata information(https://dataverse.shanghai.nyu.edu:8080/api/access/datafile/88/metadata/ddi?fileMetadataId=43&key=9aeb3106-d30d-462c-9d7b-6e6e386a15e0).

I tried to find piwik.js file with the "find" command in my server but it found noting. Anyone knows how to deal with it?

**Comment by ChenYi-qy** [comment]
Hi~ 
I handed the problem of "piwik.js" problem by uploading related files(piwik.js and piwik.php) to my server. But the metadata problem still exists, I front Apache with payara so that any host that want to access my website must through port 443 or 80,
from below console message:
![image](https://user-images.githubusercontent.com/58657543/160961194-c30bfe6c-fc13-4b18-9653-c1f7adf11b30.png)

It seems that data-explorer tried to access my server through port 8080 and it was blocked by apache, I tried to modify "DataExplorer_v4.20up.json" file's siteURL part to "https:xxxx:443" and reupload it. But it tells me:

`````````````````````````````````````````````````````````````````````````````
{"status":"ERROR","message":"Unknown reserved word: https://dataverse.shanghai.nyu.edu:443"}[root@localhost dataverse-data-explorer-v2]
`````````````````````````````````````````````````````````````````````````````

Is there any  methods to force it to access port 443?

**Comment by kaitlinnewson** [comment]
Hi @ChenYi-qy, did you update the external tool URL in your Dataverse database as well? Once you have installed the tool there should be an entry for it in the `externaltool` table of the database.

You can ignore the Piwik errors - that is not causing the metadata issue. No need to set that up if you don't want to use it.

**Comment by lubitchv** [comment]
Hi @ChenYi-qy, as @kaitlinnewson mentioned the problem you have is not with piwik. The problem is in your Dataverse configuration.
One can see that you have parameter siteUrl=http://dataverse.shanghai.nyi.edu:8080 The port 8080 should be removed.
You have to check you dataverse jvm configuration parameters, dataverse.siteUrl and dataverse.fqdn
To see your dataverse parameter, run from your glasfish directory:
./bin/asadmin list-jvm-options

You can do ` ./bin/asadmin list-jvm-options | grep siteUrl`
`dataverse.Url parameter` should be configured to` http://dataverse.shanghai.nyi.edu without 8080.`
For example:
```
./bin/asadmin delete-jvm-options '-Ddataverse.siteUrl=http\://${dataverse.fqdn}\:8080'
./asadmin create-jvm-options '-Ddataverse.siteUrl=http\://dataverse.shanghai.nyi.edu' 
```

**Comment by yizreel-Chen** [comment]
Hi@[kaitlinnewson](https://github.com/kaitlinnewson),@[lubitchv](https://github.com/lubitchv)~

It does the problem of JVM option: siteUrl, I removed port 8080 and restart again and finally it worked. 

Thanks for eveyone's help!
