### ISSUE TITLE
Cross tabulation remains empty?

### ISSUE THREAD

**Issue by tjouneau** [scholarsportal/dataverse-data-explorer-v2#4]
Hi
Apologies for the duplicate with a recently sent email.
As I am quite new to this please forgive any inaccuracy. This looks promising but I don't manage to make it work. Blame it on me, probably.
I'm taking the first (complete) file in this dataset as a base : https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.80240/FK2/MFAASB
UNF:6:/lc3kmcXnr0yujpAruayfw==

1. In the first version, as soon  as you choose two relevant variables (here gender and birth province) you get a nice graph and table for each one of them (not crossed unfortunately, ie there's no repartition by gender inside each province).
I tried to reproduce this in version 2 :
- you have to explicitly click on "summary stats", am I correct? I preferred the dynamics of having the graphs served right after field selection.
- the gender variable gives nothing ; the birthProvince gives the same as above.

2. I tried the cross tabulation with these two variables. I put them respectively in "rows and "columns". 
First remark, there's nowhere to specify a field for values (in that case the relevant value would be the number of records).
Second remark, the resulting table is empty.
What am I missing, in both cases?

Thanks in advance for your time.

Thomas

**Comment by kaitlinnewson** [comment]
Hi @tjouneau, thank you for testing things out! We are currently working on making cross-tabulations work for excel files, so you're not missing anything. Since these files don't have categories in the same way an SPSS file would, we need to do some work to generate these categories and bring them into the cross-tabulation table.

And yes, you do have to click on summary stats to see the stats for multiple variables. We will think about how we can make this more clear in the app.

**Comment by kaitlinnewson** [comment]
Hi @tjouneau, we have now added cross-tabulation for excel files which generates the required categories.
